---
- hosts: all:localhost:photon
  become_user: root
  vars:
    logstash_server: "172.28.7.111"
    logstash_port: 514
    tdnf_config:
      makecache: no
      distrosync: no
      packages:
        - sudo
        - bindutils
        - openssl-c_rehash
        - ansible
        - ansible
        - python-pip
        - vim
        - vim-extra
        - iputils
        - nfs-utils
        - logrotate
        - wget
        - ntp
        - tzdata
    timesync:
      timezone: 'America/New_York'
      servers:
        - 172.28.5.2
        - 172.28.5.3
        - 172.28.6.2
        - 172.28.6.3
      fallback_servers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
        - 3.pool.ntp.org

  tasks:
    #
    # Ensure operation only on Photon hosts
    #
    - name: Ensuring we only run on a Photon OS
      block:
        - name: Configure Role 'Photon'
          include_role:
            name: photon
      when: ansible_distribution == 'VMware Photon OS'
      rescue:
        - debug:
          msg: 'No action to take because system is not Photon'
