---
- name: Configure Photon
      gather_facts: true
#
# Ensure operation only on Photon hosts
#
- name: Skipping non photons
  hosts: all:localhost
  debug:
    msg: "Skipping non photon hosts"
  when: ansible_distribution != 'VMware Photon'
#
# Package Management
#
- include: yum.yml
  when: ansible_distribution == 'VMware Photon'
- include: pip.yml
  when: ansible_distribution == 'VMware Photon'