---

- name: Configure Photon
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Process variables
      include_vars:
        dir: vars
        extensions:
          - yml   

    - name: Update default Photon packages to latest
      command: tdnf -y distro-sync

    - name: Make a tdnf cache
      command: tdnf -y makecache

    - name: Add additional packages
      command: "tdnf info installed | grep -q \"Name\\s*:\\s*{{ item }}$\" echo true || | tdnf install -y {{ item }} | echo false"
      register: is_installed
      changed_when: is_installed
      with_items: "{{ photon_packages }}"
      