---

- name: Configure Photon
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Process variables
      include_vars:
        dir: vars
        extensions:
          - yml   

    - name: Update default Photon packages to latest
      command: tdnf -y distro-sync

    - name: Make a tdnf cache
      command: tdnf -y makecache

    - name: Add additional packages
      command: tdnf install -y {{ item }}
      with_items: "{{ photon_packages }}"
      when: tdnf info installed | grep  \"Name\s*:\s*{{ item }}$\"^C

 