---
- hosts: all:localhost:photon
  become_user: root
  vars:
    logstash_server: "172.28.7.111"
    logstash_port: 514
    tdnf:
      makecache: true
      distrosync: true
      packages:
        - bindutils
        - sudo
        - openssl-c_rehash
        - vim
        - nfs-utils
        - ansible
        - python-pip
        - vim-extra
        - iputils
        - logrotate

  tasks:
    #
    # Ensure operation only on Photon hosts
    #
    - name: Skipping Non-Photon machine (group 'photons') - {{ ansible_distribution }}
      debug:
        msg: "Skipping non photon host {{ ansible_distribution }}"
      when: ansible_distribution != 'VMware Photon OS'

    - name: Configure Role 'Photon'
      include_role:
        name: photon
