---

- name: Configure Photon
  gather_facts: true
  hosts: localhost
  tasks:

    - name: Process variables
      include_vars:
        dir: vars
        extensions:
          - yml   

    #- name: Update default Photon packages to latest
    #  command: tdnf -y distro-sync

    #- name: Make a tdnf cache
    #  command: tdnf -y makecache

    - name: Add additional packages
      shell: "[[ $(tdnf info installed | grep -q \"Name\\s*:\\s*{{ item }}$\"; echo $?) == 0 ]] && echo false || (tdnf install -y {{ item }} && echo true)"
      register: is_installed
      changed_when: is_installed.stdout|bool
      with_items: "{{ photon_packages }}"
    
    - debug:
        msg: "is_installed: {{is_installed}}"
    

      