#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#

#---------------------------
# Docker Settings
#---------------------------
docker_config:
  # prevent doing things that will break under docker.
  # specifically added so that travis-ci can test inside docker
  photon_testing_in_docker: no
  # docker group id (gets created) for socket access and similar
  group_id: 995
  # Insecure registries docker is allowed to connect to
  insecure_registries: []
  # Docker Daemon Config
  daemon_config:
    log-driver: "json-file"
    log-opts:
      max-size: "10m"
      max-file: "1000"

#------------------
# tdnf Settings
#------------------
tdnf_config:
  # Create a cache of the configured sites for faster searching
  makecache: no
  # Update all installed packages to the latest in the current distribution
  distrosync: no

#------------------
# Syslog forwarding Settings
#------------------
syslog_config:
  # Server/IP to forward syslog to
  server:
  # Port to forward syslog to
  port: 514
  # File to log locally to.  If unset, won't log to a file
  local_file: /var/log/messages

#------------------
# timesync/timezone Settings
#------------------
timesync_config:
  # Timezone to set OS to (use TZdata values)
  timezone: "Etc/UTC"
  servers:
    - 172.28.5.2
    - 172.28.5.3
    - 172.28.6.2
    - 172.28.6.3
  fallback_servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

#------------------
# tdnf Settings
#------------------
tdnf_config:
  updatecache: no
  distrosync: no
  packages:
    - sudo
    - bindutils
    - openssl-c_rehash
    - ansible
    - python-pip
    - vim
    - vim-extra
    - iputils
    - nfs-utils
    - logrotate
    - wget
    - ntp
    - tzdata
  additional_packages: []

#------------------
# SSL Certificate settings
#------------------
ssl_config:
  # Inline certificate (Include Begin and End Certificate lines)
  ssl_root_certificate_pem: 
  # Name of the certifcate to be stored in /etc/ssl/certs
  ssl_root_certificate_pem_filename: 