---
#
# Import configuration
#
  - name: Import configuration to implement
    hosts: all:localhost
    include_vars:
      dir: vars
      file: tdnf.yml
#
# Update packages to the latest release of photon
#
  - name: Update installed Photon packages to latest distribution
    hosts: all:localhost
    command: tdnf -y distro-sync
    when: tdnf.distrosync and true
#
# Create a tdnf cache for faster searching
#
  - name: Create a tdnf cache for faster searching
    hosts: all:localhost
    command: tdnf -y makecache
    when: tdnf.makecache and true
#
# Install additional packages
#
  - name: Add additional packages
    hosts: all:localhost
    shell: "[[ $(tdnf info installed | grep -q \"Name\\s*:\\s*{{ item }}$\"; echo $?) == 0 ]] && echo false || (tdnf install -qy {{ item }} && echo true)"
    register: is_installed
    changed_when: is_installed.stdout|bool
    with_items: "{{ tdnf.packages }}"
    when: tdnf.packages && tdnf.packages|length > 0