#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
# -------- package management
- include: tdnf.yml
- include: pip.yml

# -------- docker setup
- include: docker.yml
  when: photon_with_docker and not photon_testing_in_docker

# -------- log forwarding support
- include: logstash.yml
  when: logstash_server is defined

# -------- configure basic iptables rules
- include: iptables.yml

# -------- configure timesync
- include: timesync.yml

# -------- Install local ssl root certificate
- include: certificates.yml
