#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- name: Skipping non Photons
  debug:
    msg: "Skipping non photon hosts because distro is {{ ansible_distribution }}"
  when: ansible_distribution != 'VMware Photon OS'

# -------- package management
- include: tdnf.yml
#  when: ansible_distribution == 'VMware Photon OS'
#- include: yum.yml
#  when: ansible_distribution == 'VMware Photon OS'

- include: pip.yml
#  when: ansible_distribution == 'VMware Photon OS'


# -------- docker setup
- include: docker.yml
#  when: ansible_distribution == 'VMware Photon OS' and 
  when: photon_with_docker and not photon_testing_in_docker


# -------- logstash support
- include: logstash.yml
#  when: ansible_distribution == 'VMware Photon OS' and 
  when: logstash_server is defined

# -------- configure basic iptables rules
- include: iptables.yml

# -------- configure timesync
- include: timesync.yml