---
- name: Install NTP demon
  tdnf:
    name: ntp tzdata

- name: Ensure that ntp is started and enabled on restart
  Service:
    name: ntp
    state: started
    enabled: yes

- name: Set timezone to {{ ntp.timezone }}
  timezone:
    name: "{{ ntp.timezone }}"

- name: Set NTP configuration in /etc/systemd/timesyncd.conf
  lineinfile:
    dest: /etc/systemd/timesyncd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line   }}"
    insertafter: '\[Time\]'
    backrefs: Yes
    create: True
    state: present
  with_items:
    - regexp: '^\s*#?\s*(NTP=).*$'
      line: 'NTP={{ ntp.servers | join(" ") }}'

    - regexp: '^\s*#?\s*(FallbackNTP=).*$'
      line: 'FallbackNTP={{ ntp.fallback_servers | join(" ") }}'

  notify:
    - reload timesyncd ntp
    - restart timesyncd
    - sync RTC
