#
# Default Package Installs
#
---
#
# Update packages to the latest release of photon
#
- name: Update installed Photon packages to latest distribution
  command: tdnf -y distro-sync
  update_cache: yes
  when: tdnf_config.distrosync

#
# Update all existing packages
#
- name: "Update all existing packages"
  tdnf:
    upgrade: yes

#
# Install additional packages
#
- name: Add additional packages
  tdnf:
    name: "{{ tdnf_config.packages }}"
    state: present
  when:
    - tdnf_config.packages
    - tdnf_config.packages|length > 0