---
#
# Update packages to the latest release of photon
#
- name: Update installed Photon packages to latest distribution
  command: tdnf -y distro-sync
  when: tdnf-config.distrosync
#
# Create a tdnf cache for faster searching
#
- name: Create a tdnf cache for faster searching
  command: tdnf -y makecache
  when: tdnf-config.makecache

#
# Update all existing packages
#
- name: "Update all existing packages"
  tdnf:
    upgrade: true

#
# Install additional packages
#
- name: Add additional packages
  tdnf:
    name: "{{ tdnf-config.packages}}"
    state: latest
    update_cache: true
  when:
    - tdnf-config.packages
    - tdnf-config.packages|length > 0
