#
# Default Package Installs
#
---
#
#  Update Repo Cache
#
- name: Update tdnf repository cache
  tdnf:
    update_cache: yes
  when: tdnf_config.makecache | bool

- name: update systemd to fix network daemon crashes
  tdnf:
    name: systemd
    state: present

#
# Update all existing packages
#
- name: Update all installed packages to repository latest
  tdnf:
    upgrade: yes
    update_cache: yes
  when: tdnf_config.distrosync | bool

#
# Install additional packages
#
- name: Add additional packages
  tdnf:
    name: "{{ tdnf_config.packages }}"
    state: present
  when:
    - tdnf_config.packages
    - tdnf_config.packages|length > 0
