---
#
# Update packages to the latest release of photon
#
  - name: Update installed Photon packages to latest distribution
    command: tdnf -y distro-sync
    when: tdnf.distrosync
#
# Create a tdnf cache for faster searching
#
  - name: Create a tdnf cache for faster searching
    command: tdnf -y makecache
    when: tdnf.makecache
#
# Install additional packages
#
  - name: Add additional packages
    shell: "[[ $(tdnf info installed | grep -q \"Name\\s*:\\s*{{ item }}$\"; echo $?) == 0 ]] && echo false || (tdnf install -qy {{ item }} && echo true)"
    register: is_installed
    changed_when: is_installed.stdout|bool
    with_items: "{{ tdnf.packages }}"
    when: 
      - tdnf.packages 
      - tdnf.packages|length > 0