---
#
# Update packages to the latest release of photon
#
  - name: Update installed Photon packages to latest distribution
    command: tdnf -y distro-sync
    when: tdnf.distrosync
#
# Create a tdnf cache for faster searching
#
  - name: Create a tdnf cache for faster searching
    command: tdnf -y makecache
    when: tdnf.makecache
#
# Install additional packages
#
  - name: Add additional packages
    tdnf:
      name: '{{ tdnf.packages}}'
      state: latest
      update_cache: true
    when: 
      - tdnf.packages 
      - tdnf.packages|length > 0