---
- name: Remove expiry time for root
  user:
    name: root
    expires: -1
    password_expire_max: 999999

- name: Apply any user SSH keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  with_items: "{{ ssh_enabled_users }}"